### ISSUE TITLE
Persistent error in RDP connections to the machine without pre-defined credentials

### ISSUE THREAD

**Issue by Hu3cx** [casdoor/awesome-auth#130]
#128  the solution didn't work. friends, thank you for taking the time to help us users of the application, but unfortunately these connection solutions are not working, try to simulate the error by creating a new connection and pre-defining the credentials to enter the machine to understand better. I don't know if I'm communicating incorrectly because I don't speak English fluently. However, the problem occurs when we follow these steps: we add a new connection (both RDP and SSH), configure it with the host, and leave the login and password fields empty. After that, when we try to connect, even with the correct credentials, it returns an error saying the credentials are wrong.

![image](https://github.com/user-attachments/assets/f923822a-2d3f-472c-b5aa-fe3626169e70)
![image](https://github.com/user-attachments/assets/ce47cfbb-10c7-4d49-b53c-926e37680f53)
![image](https://github.com/user-attachments/assets/8df93f15-8c59-4f66-890e-af21dec2d529)
![image](https://github.com/user-attachments/assets/d086b847-510f-4388-b6f5-27346b425ae8)

**Comment by leo220yuyaodog** [comment]
@Hu3cx Thanks for your feedback, the bug should have been fixed by now. The following is the screen recording of my using the latest version to connect to the remote machine using  SSH and RDP respectively. Please check whether it is consistent with the reproduction process you expected. If you still have problems, make sure your casvisor is updated to the latest version.

https://github.com/user-attachments/assets/4f65bab8-0350-4980-bc87-06dc815bc91e

**Comment by Hu3cx** [comment]
One important point I think I forgot to mention is that I am using Docker. Was the image updated?

**Comment by Hu3cx** [comment]
I am using Docker, I am still a bit new to it, but after he deployed the fix, should he have updated something in the image to reflect it for me as well? If the answer is yes, I think that's why mine might not be working correctly

**Comment by Hu3cx** [comment]
@hsluoyz @leo220yuyaodog  One more important detail is that I am using synchronized AD users, in this case, my own user to log into a server with the Active Directory credentials. It is not a user created directly in Casdoor.

**Comment by hsluoyz** [comment]
@Hu3cx you should use the latest version v1.58.0: https://github.com/casvisor/casvisor/releases/tag/v1.58.0

**Comment by leo220yuyaodog** [comment]
> I am using Docker, I am still a bit new to it, but after he deployed the fix, should he have updated something in the image to reflect it for me as well? If the answer is yes, I think that's why mine might not be working correctly

If you use docekr, please use the image version v1.58.0

**Comment by Hu3cx** [comment]
I am already using the latest version. In my logs, it appears that the password is not being passed. I have recreated the images, the containers, and even modified the Dockerfile, but the behavior remains the same. Sorry for the inconvenience, but could you test by entering the credentials and with a user that synchronizes with LDAP if possible?
![image](https://github.com/user-attachments/assets/ad88d4d4-304e-4e38-ab5f-6243a58bf6ed)

**Comment by Hu3cx** [comment]
I'm using the latest version
![image](https://github.com/user-attachments/assets/9f0dd7ec-cf70-4b08-904e-53f869fc2bfb)

**Comment by Hu3cx** [comment]
Well, I've tested everything here, the only thing I didn't do was change machines or format the machine I'm using to create the environment, but without success. I ask that you please, if possible, take another look at this case carefully, and test using LDAP (not that this is 100% the case but perhaps it would help)

**Comment by Hu3cx** [comment]
I have a question: is there any NLA (Network Level Authentication) rule when credentials are saved when creating a machine? If so, are these rules being applied when I don't fill in the credentials? I tested it on other servers, and it seems the connection worked, but I think there might be a rule that's not behaving as expected.
![image](https://github.com/user-attachments/assets/930f5d25-7972-4268-a17b-c052f49a1fda)

**Comment by Hu3cx** [comment]
![image](https://github.com/user-attachments/assets/72ce0ab6-aae8-43e1-ad33-eac0d87b05ef)

**Comment by Hu3cx** [comment]
@hsluoyz  @leo220yuyaodog  This is because I'm using Windows Server. I think there is this small difference as to why it works for some people and why it doesn't work for others.

**Comment by leo220yuyaodog** [comment]
> I have a question: is there any NLA (Network Level Authentication) rule when credentials are saved when creating a machine? If so, are these rules being applied when I don't fill in the credentials? I tested it on other servers, and it seems the connection worked, but I think there might be a rule that's not behaving as expected. ![image](https://private-user-images.githubusercontent.com/68939737/351795956-930f5d25-7972-4268-a17b-c052f49a1fda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NzI3NTAsIm5iZiI6MTcyMTg3MjQ1MCwicGF0aCI6Ii82ODkzOTczNy8zNTE3OTU5NTYtOTMwZjVkMjUtNzk3Mi00MjY4LWExN2ItYzA1MmY0OWExZmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAxNTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZjIwNmJlODkzYWRhMmMzYjYyNDE2YWJiNzFjOTU2NzM0ZGRjNWI2YTNlMzRmZDU4ZjQ3ZGYxNmM3YzllNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wrD4FzrimltXz579I7vy3RLy3sg72HmvZQxPI3xfHqQ)

The logs you posted is similar to the problem mentioned in this link, you can see if it works for you. 
https://issues.apache.org/jira/browse/GUACAMOLE-1357

**Comment by Hu3cx** [comment]
I identified the problem, and it seems to be something related to the credentials. I will try to resolve it internally on the server, and if it doesn't work and it's really an issue with the application, I will get back to you. Thank you very much for the support.
