### ISSUE TITLE
[feature] support showing VMware virtual machines in machine list and edit pages

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/awesome-auth#139]
Need to support getting machine info from VMware Workstation Pro via their REST API: https://docs.vmware.com/en/VMware-Workstation-Pro/17/com.vmware.ws.using.doc/GUID-9FAAA4DD-1320-450D-B684-2845B311640F.html

Similar to Aliyun: https://github.com/casvisor/casvisor/commits/master/

![image](https://github.com/user-attachments/assets/769773aa-4213-4777-8d8c-43599ed9fee1)

The final goal is to be able to list VMware VMs here: https://door.casvisor.com/machines

**Comment by Gexinyu2333** [comment]
#140

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casvisor/casvisor/pull/140
