### ISSUE TITLE
Disconnect session and upload/download in RDP Session

### ISSUE THREAD

**Issue by HRNasr** [casdoor/awesome-auth#14]
for work better with RDP Session need two feature for session management:
1- Disconnect Session
2- Upload / Download

**Comment by hsluoyz** [comment]
Yes, I found there's no way to disconnect the RDP: https://door.casvisor.com/access/casbin/test-machine4 . I usually close the browser tab, is this "disconnect"?


![image](https://github.com/casvisor/casvisor/assets/3787410/73a7fae1-812f-4bcc-b34c-7c5fb10b1bbd)

**Comment by hsluoyz** [comment]
Closing the browser tab will disconnect the session. Or admin can stop a user's session like:

![2f29c355d88046451646a50042ede039](https://github.com/casvisor/casvisor/assets/3787410/032151af-a7d2-425b-b1a0-60c56e075dce)

**Comment by hsluoyz** [comment]
For upload/download, replaced by: https://github.com/casvisor/casvisor/issues/52
