### ISSUE TITLE
Change casdoor config in front end after the deploy

### ISSUE THREAD

**Issue by HRNasr** [casdoor/awesome-auth#15]
Frontend code written for a React project with default casdoor settings when compiled. If we want to change the addresses related to casdoor after being placed on the operational server, how should we do it?

**Comment by hsluoyz** [comment]
@HRNasr fixed by: https://github.com/casbin/casvisor/commit/5030a02d77b5d8c5039139b7fae4d5bd7d9416f8

**Comment by HRNasr** [comment]
How is work?
frontend read casdoor config from conf.js !!!!

**Comment by hsluoyz** [comment]
See code: https://github.com/casbin/casvisor/commit/5030a02d77b5d8c5039139b7fae4d5bd7d9416f8, let GPT explain to you

**Comment by HRNasr** [comment]
tnx.
