### ISSUE TITLE
[feature] add Swagger page

### ISSUE THREAD

**Issue by HRNasr** [casdoor/awesome-auth#17]
Setting up Swagger for easier management of API commands between frontend and backend

Refer to Casdoor: https://casdoor.org/docs/developer-guide/swagger/

Demo: https://door.casdoor.com/

![image](https://github.com/casvisor/casvisor/assets/3787410/63bff6ec-a93b-458f-b841-01b1ade10e50)

https://door.casdoor.com/swagger/

**Comment by hsluoyz** [comment]
@HRNasr why close?

**Comment by hsluoyz** [comment]
@HRNasr do you want to create a PR by yourself? see: https://casdoor.org/docs/developer-guide/swagger/
