### ISSUE TITLE
It is not compatible with Amazon Linux 2023.

### ISSUE THREAD

**Issue by Akshat111111** [casdoor/awesome-auth#21]
It does not work with Amazon Linux 2023.
I tried manually adding libraries but was unsuccessful.
I'm not sure whether anyone else is experiencing the same problem.

https://aws.amazon.com/linux/amazon-linux-2023/

**Comment by hsluoyz** [comment]
@Akshat111111 what error did you encounter?

**Comment by Akshat111111** [comment]
I am unable to use it If I use it with Amazon Linux, It is getting closed unnecesarily.I am working on  it, whether its the problem of my local system or this particular software.

**Comment by hsluoyz** [comment]
@Akshat111111 what do you mean? Do you mean deploying Casvisor on Amazon Linux 2023? Or deploying Guacamole in Amazon Linux 2023? Or using Casvisor to connect RDP/VNC to a Amazon Linux 2023 machine?

**Comment by Akshat111111** [comment]
Using casvisor to connect RDP/VNC

**Comment by hsluoyz** [comment]
@Akshat111111 can you directly provide all info instead of asking one by one? Like

- What protocol?
- What error did you see? Screenshot or video?

**Comment by Akshat111111** [comment]
Hey, Now its working perfectly fine. The issue is with another application due to which this application is being lagging and interrupted.

**Comment by hsluoyz** [comment]
@Akshat111111 great to see resolved!
