### ISSUE TITLE
Session Size (RDP, SSH) in Android

### ISSUE THREAD

**Issue by HRNasr** [casdoor/awesome-auth#43]
Bug:   The size of RDP, SSH Sessions is not displayed correctly on mobile (Android) and does not cover the entire screen

**Comment by hsluoyz** [comment]
@HRNasr can you provide a screenshot or demo video for this?

**Comment by HRNasr** [comment]
Please see the size of session in picture:
![20240204_133607](https://github.com/casbin/casvisor/assets/17843262/72807593-5df4-42de-9d05-97442a3b4906)
![20240204_133526](https://github.com/casbin/casvisor/assets/17843262/0bce14f2-8755-45df-a201-87598db01591)

**Comment by hsluoyz** [comment]
@HRNasr can you test the `rdp-test` asset in demo site: https://demo.casvisor.com/ ? I think the latest code has fixed this issue.

See my Android phone (User-Agent is: `Mozilla/5.0 (Linux; U; Android 14; zh-cn; 23116PN5BC Build/UKQ1.230804.001) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.118 Mobile Safari/537.36 XiaoMi/MiuiBrowser/17.8.211101 swan-mibrowser`)

![daac7a0ecb3a85dddd812393fca5da7](https://github.com/casbin/casvisor/assets/3787410/14570aee-9505-4da0-8ed9-935dd05171db)

**Comment by hsluoyz** [comment]
Closed for now
