### ISSUE TITLE
logout user not disconnect session

### ISSUE THREAD

**Issue by HRNasr** [casdoor/awesome-auth#44]
If the user is disconnected by himself or for other reasons, his established sessions will not be interrupted/Disconnect and will continue to work

**Comment by hsluoyz** [comment]
@HRNasr what do you mean by "disconnected by himself"? Like closing the browser?

**Comment by HRNasr** [comment]
Yes. user logout or session timeout

**Comment by hsluoyz** [comment]
@HRNasr can you try the latest code? I think it has been fixed

**Comment by hsluoyz** [comment]
Closed as resolved
