### ISSUE TITLE
feature: add "upload and downlod RDP file" feature

### ISSUE THREAD

**Issue by HRNasr** [casdoor/awesome-auth#45]
Added some shortcut to session for:
1-Disconnect session  /Logout
2-Upload for RDP
3-Download for RDP
4-Ctrl + C
5-Ctrl + V
6-Alt +Tab

**Comment by hsluoyz** [comment]
@HRNasr all are supported already except below:

```
2-Upload for RDP
3-Download for RDP
```

**Comment by HRNasr** [comment]
Yes. correct
Please add this feature
