### ISSUE TITLE
Size of window session not correct and small

### ISSUE THREAD

**Issue by HRNasr** [casdoor/awesome-auth#7]
when open rdp/vnc session, size of window not correct (width page)  and when full screen and back from full screen  is correct

**Comment by hsluoyz** [comment]
@HRNasr can you provide a demo video?

**Comment by HRNasr** [comment]
![Shot 0221](https://github.com/casbin/casvisor/assets/17843262/7c4c5cd1-fcac-4872-a96f-fb0250556a8e)

**Comment by HRNasr** [comment]
![Shot 0220](https://github.com/casbin/casvisor/assets/17843262/0c42afdf-7800-48fd-9f53-4710d7ef04a9)

**Comment by HRNasr** [comment]
picture of session when open in new window  (not full page and need fullsreen and back )

**Comment by hsluoyz** [comment]
@HRNasr I don't see anything wrong with the pictures

**Comment by HRNasr** [comment]
It is not better to use the whole screen as shown below
![Shot 0215](https://github.com/casbin/casvisor/assets/17843262/e820154f-0cb3-4b90-9f8f-699006a38564)

**Comment by HRNasr** [comment]
width * height   page

**Comment by HRNasr** [comment]
resolve with last version
