### ISSUE TITLE
Question: Open session in Tabs format in main window

### ISSUE THREAD

**Issue by HRNasr** [casdoor/awesome-auth#8]
Sessions can be opened on the main page in the form of a Tabs (Multiple Tabs Page)so that we can manage systems more easily on one window without switch between window

**Comment by hsluoyz** [comment]
@HRNasr can you provide a demo picture or video about the tabs you want?

**Comment by HRNasr** [comment]
![Shot 0215](https://github.com/casbin/casvisor/assets/17843262/e0a19079-4871-44dd-8add-17c747587181)

**Comment by HRNasr** [comment]
example  above picture

**Comment by HRNasr** [comment]
Film of desired feature
           https://www.youtube.com/watch?v=R5uCPrH9mnw
Best feature of this is:

1. Multiple tab for session
2. Ability to move Tabs horizontally and vertically to work with multiple servers at the same time

**Comment by hsluoyz** [comment]
@HRNasr like this? https://github.com/paidem/guacozy

**Comment by HRNasr** [comment]
yes

**Comment by HRNasr** [comment]
Ability to move Tabs horizontally and vertically to work with multiple servers at the same time
![Shot 0214](https://github.com/casbin/casvisor/assets/17843262/48f6fbd9-68d9-410b-b256-be615ada9dd1)

**Comment by hsluoyz** [comment]
Already done long ago: https://door.casvisor.com/workbench

![image](https://github.com/casvisor/casvisor/assets/3787410/2b209237-ed14-454b-ad96-91adad4bbbbf)
