### ISSUE TITLE
feature: use HashiCorp Vault to store asset password

### ISSUE THREAD

**Issue by HRNasr** [casdoor/awesome-auth#80]
If we use a password vault to store the username and password of the servers, the security of the service will increase

**Comment by hsluoyz** [comment]
@HRNasr what kind of secret vault are you talking about?

**Comment by HRNasr** [comment]
Yes, you are right. I mean something similar to this:
[Vault by HashiCorp](https://www.vaultproject.io/)

Of course, within the usual facilities for storing usernames and passwords
