### ISSUE TITLE
Database migration

### ISSUE THREAD

**Issue by HRNasr** [casdoor/awesome-auth#81]
Database migration for data

**Comment by hsluoyz** [comment]
@HRNasr what do you mean?

**Comment by HRNasr** [comment]
Having a mechanism for database migration. Currently, this is done for the schema. But I think it cannot be done for data

**Comment by hsluoyz** [comment]
@HRNasr you should use more professional tools for data migration. I don't think Casvisor should be that kind of professional DB client. Currently it's not planned for now.
