### ISSUE TITLE
Support Web protocol for auditing and control

### ISSUE THREAD

**Issue by HRNasr** [casdoor/awesome-auth#82]
Some of the systems that network administrators use to discuss monitoring and management are web-based systems. It can be interesting to tweak and support access to web protocols (HTTP(S)) along side existing features

**Comment by hsluoyz** [comment]
@HRNasr I don't get what you said. Can you explain it a little bit more?

**Comment by HRNasr** [comment]
The purpose is to implement a mechanism like reverse proxy for websites. which can be interesting along with the available capabilities to access the supported protocols(RDP, SSH). Or maybe it can be a combination with CasWAF

**Comment by hsluoyz** [comment]
@HRNasr the gateway fearure is in: https://github.com/casbin/caswaf
