### ISSUE TITLE
feature: add file manager to Casvisor

### ISSUE THREAD

**Issue by HRNasr** [casdoor/awesome-auth#83]
Support File Access on assets for Access Control and Auditing.
with features  ex: control add/edit/delete/rename/ ... files in assets
 
Ex: SMB Protocol

**Comment by HRNasr** [comment]
It means something similar:
Web File Browser

https://github.com/filebrowser/filebrowser
https://github.com/mickael-kerjean/filestash

**Comment by hsluoyz** [comment]
@HRNasr 

Update
====

After second thought, I think iframe may be slow in UX. So we still put the frontend code and backend code in application like Casvisor.

- Casibase frontend code: https://github.com/casibase/casibase/blob/master/web/src/FileTree.js
- Casibase backend code: https://github.com/casibase/casibase/tree/master/storage

We can copy the entire above code to Casvisor project. So it gains native experience, and it's easy for us to update code or keep consistency between projects.

About SMB client, we can use libraries like below. Use the mature one

- https://github.com/hirochachacha/go-smb2
- https://github.com/stacktitan/smb



Original
====

we will put this file manager feature to Casdoor, using Casdoor storage provider: https://door.casdoor.com/providers/admin/provider_storage_local_file_system and 

and Casibase file tree: https://demo-admin.casibase.com/stores/admin/store-built-in

1. Casibase file tree will move to Casdoor
2. Casibase uses the file tree provided by Casdoor (like via iframe)
3. Casvisor uses the file tree provided by Casdoor (like via iframe)

![image](https://github.com/casvisor/casvisor/assets/3787410/ebdded89-f867-4bc7-bbe5-b3e60642137d)
